server:
  port: 8089
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:

  datasource:
    generate-unique-name: false
    name: traderstat
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:traderstat;DB_CLOSE_DELAY=-1
    username: admin
    password: admin
    # tcp: jdbc:h2:tcp://localhost:9092/mem:traderstat

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always